Additional options native embeddings
ZachNagengast/similarity-search-kit pull request #23
Opened 2023-10-31 12:24 UTC by BernhardEisvogel

Hey everyone!

I want to use this repository in a language program that need the word embedding instead of the sentence embedding, so I changed a way to switch between those two modes in NativeEmbeddings.init.

Greetings Bernhard
P.s. I'm new to Github

2023-11-02 16:55 UTC, ZachNagengast requested changes
Hey @BernhardEisvogel, great idea! I just made couple suggestions for edits, otherwise looks great!

2023-11-02 16:55 UTC, ZachNagengast commented on Sources/SimilaritySearchKit/Core/Embeddings/Models/NativeEmbeddings.swift
> +    public init(language: NLLanguage = .english, type:NativeEmbeddingType = .sentenceEmbedding) {
```suggestion
    public init(language: NLLanguage = .english, type: NativeEmbeddingType = .sentenceEmbedding) {
```

2023-11-02 16:55 UTC, ZachNagengast commented on Sources/SimilaritySearchKit/Core/Embeddings/Models/NativeEmbeddings.swift
> +                    guard let nativeModel = NLEmbedding.sentenceEmbedding(for: language) else {
```suggestion
                case .wordEmbedding:
                    guard let nativeModel = NLEmbedding.wordEmbedding(for: language) else {
```

Is this the model you wanted to use?

2023-11-02 16:55 UTC, ZachNagengast commented on Sources/SimilaritySearchKit/Core/Embeddings/Models/NativeEmbeddings.swift
> +        init(language: NLLanguage, type:NativeEmbeddingType = .sentenceEmbedding) {
```suggestion
        init(language: NLLanguage, type: NativeEmbeddingType = .sentenceEmbedding) {
```

2023-11-07 19:08 UTC, BernhardEisvogel commented
Great! I will upload another commit later improving the performance of the search algorithm, currently it's ordering the complete list and then it takes "the best" k entries( in  O(nlogn) )but it's sufficient to use some topK algorithm ( in O(n) )

2023-11-07 19:47 UTC, ZachNagengast approved these changes
Looks good! Thanks @BernhardEisvogel

2023-11-07 19:48 UTC, merged